AWSTemplateFormatVersion: "2010-09-09"
Description: "CF Script to create CI/CD pipeline."

Parameters:
  ArtifactStore:
    Type: String
    Default: akeem-24
    Description: S3 bucket for code pipeline artifact location

  CodeBuildProject:
    Type: String
    Default: CiCdProject
    Description: Name of code build project

  ConnectionArn:
    Type: String
    Default: "arn:aws:codestar-connections:us-east-2:450082263787:connection/e3ab02ff-343e-437f-9b1c-c356ac94fa5d"
    Description: Connection Arn to connect to github

  RepositoryId:
    Type: String
    Default: "Princeakkeem/sample-service"
    Description: Repository id

  RepositoryBranch:
    Type: String
    Default: master
    Description: Branch for repository

Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "*"
                Effect: Allow
                Resource: "*"

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactStore
        Type: S3
      Name: "cicd-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceGithub
              RunOrder: 1
              Namespace: SourceVariables
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref RepositoryId
                BranchName: !Ref RepositoryBranch
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: CodeBuild
          Actions:
            - Name: SourceBuild
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Namespace: BuildVariables
        - Name: CodeDeploy
          Actions:
            - Name: SourceDeploy
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              Configuration:
                ClusterName: SampleCluster
                ServiceName: SampleService
                FileName: imagedefinitions.json
              InputArtifacts:
                - Name: BuildArtifact
              Namespace: DeployVariables
              Region: "us-east-2"
